### ISSUE TITLE
Persist the data model

### ISSUE THREAD

**Issue by knatten** [knatten/ChoreScore#2]
So it doesn't disappear when the app is closed

**Comment by knatten** [comment]
Noting down the issues I'm having with this for tomorrow:
- Install the app on the phone
- Give Bob 3 points
- Background the app
- `Save()` reports `Result of saving file true`
- Kill the app
- Re-start the app
- `Load()` reports `{"_subscribers":[null,null],"_isLeaf":true,"_values":[{"name":"Alice","score":{"_subscribers":[null],"_isLeaf":true,"_values":[0]}},{"name":"Bob","score":{"_subscribers":[null],"_isLeaf":true,"_values":[3]}},{"name":"Eve","score":{"_subscribers":[null],"_isLeaf":true,"_values":[0]}}]}`, and `Done populating model`
- Everyone is displayed with score 0
- Give Eve 4 points
- Background the app
- `Save()` reports `Result of saving file true`
- Kill the app
- Restart the app
- `Load()` reports `{"_subscribers":[null,null],"_isLeaf":true,"_values":[{"name":"Alice","score":{"_subscribers":[null],"_isLeaf":true,"_values":[0]}},{"name":"Bob","score":{"_subscribers":[null],"_isLeaf":true,"_values":[3]}},{"name":"Eve","score":{"_subscribers":[null],"_isLeaf":true,"_values":[0]}}]}`, and `Done populating model` Note that this is the data from the first time we saved the state, not the updated state we just tried to write!
- Everyone is displayed with score 0

Here's the exception mentioned above:

```
W/System.err( 1642): android.content.pm.PackageManager$NameNotFoundException
W/System.err( 1642):    at com.lge.launcher2.homeplus.addon.HomePlusResourceManager.init(HomePlusResourceManager.java:32)
W/System.err( 1642):    at com.lge.launcher2.homeplus.addon.HomePlusResourceManager.getHomePlusDrawable(HomePlusResourceManager.java:40)
W/System.err( 1642):    at com.lge.launcher2.homeplus.addon.HomePlusInternalManager.getHomePlusDrawableFromContent(HomePlusInternalManager.java:484)
W/System.err( 1642):    at com.lge.launcher2.homeplus.addon.HomePlusInternalManager$HomePlusInterManagerImpl.getHomePlusDrawable(HomePlusInternalManager.java:280)
W/System.err( 1642):    at com.lge.launcher2.homeplus.view.HomePlusHostView.setWebViewDrawable(HomePlusHostView.java:131)
W/System.err( 1642):    at com.lge.launcher2.homeplus.view.HomePlusHostView.setInternalManager(HomePlusHostView.java:233)
W/System.err( 1642):    at com.lge.launcher2.homeplus.HomePlusManager.addHomePlusHostView(HomePlusManager.java:252)
W/System.err( 1642):    at com.lge.launcher2.homeplus.HomePlusManager.showHomePlus(HomePlusManager.java:114)
W/System.err( 1642):    at com.lge.launcher2.Workspace.showHomePlus(Workspace.java:9333)
W/System.err( 1642):    at com.lge.launcher2.Launcher.showHomePlus(Launcher.java:5132)
W/System.err( 1642):    at com.lge.launcher2.Launcher.showHomePlus(Launcher.java:5121)
W/System.err( 1642):    at com.lge.launcher2.Launcher.setState(Launcher.java:4569)
W/System.err( 1642):    at com.lge.launcher2.Launcher.showWorkspace(Launcher.java:3537)
W/System.err( 1642):    at com.lge.launcher2.Launcher.onNewIntent(Launcher.java:1807)
W/System.err( 1642):    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1161)
W/System.err( 1642):    at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2319)
W/System.err( 1642):    at android.app.ActivityThread.performNewIntents(ActivityThread.java:2332)
W/System.err( 1642):    at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2341)
W/System.err( 1642):    at android.app.ActivityThread.access$1600(ActivityThread.java:139)
W/System.err( 1642):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1271)
W/System.err( 1642):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 1642):    at android.os.Looper.loop(Looper.java:136)
W/System.err( 1642):    at android.app.ActivityThread.main(ActivityThread.java:5105)
W/System.err( 1642):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 1642):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 1642):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
W/System.err( 1642):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
W/System.err( 1642):    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by knatten** [comment]
Tried to create a minimal reproduction in 30d604cbd544c185bcdcaacb12e6bbe359ebd173, but something else happened:

Every time I tried to save, I got the exception mentioned above, and when I loaded the file again, its content had been updated. Almost like it depends on that exception to actually write the file.

However, the fourth time I tried, I got the following:

```
I/ChoreScore(25463): Loading: es6-promise-50b2740f.js
I/ChoreScore(25463): Loading: subscriberproxy-705ef316.js
I/ChoreScore(25463): Loading: observable-b4b458ef.js
I/ChoreScore(25463): Loading: window-42340274.js
I/ChoreScore(25463): Loading: windowtimers-9fb43406.js
I/ChoreScore(25463): Loading: eventtarget-bf1b1eff.js
I/ChoreScore(25463): Loading: windowbase64-2dd63ce5.js
I/ChoreScore(25463): Loading: file-870ea4a8.js
I/ChoreScore(25463): Loading: xmlhttprequest-33b4b514.js
I/ChoreScore(25463): Loading: fetch-90f6b0d0.js
I/ChoreScore(25463): Loading: localstorage-d30dc034.js
I/ChoreScore(25463): Loading data from persons.json
I/ChoreScore(25463): Loaded content from file:
I/ChoreScore(25463): {"_subscribers":[null,null],"_isLeaf":true,"_values":["four "]}
I/DEBUG   (  289): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  289): Build fingerprint: 'lge/g2_open_com/g2:4.4.2/KOT49I.D80220h/D80220h.1413914494:user/release-keys'
I/DEBUG   (  289): Revision: '10'
I/DEBUG   (  289): pid: 25463, tid: 25494, name: com.ChoreScore  >>> com.ChoreScore <<<
I/DEBUG   (  289): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadcab1
I/DEBUG   (  289):     r0 6053fbd8  r1 6053fbd8  r2 00000000  r3 deadcfff
I/DEBUG   (  289):     r4 65dccb38  r5 65dccb70  r6 65d6100c  r7 65dcdc40
I/DEBUG   (  289):     r8 6115e9d5  r9 6a671000  sl 65dcdc78  fp 400e82ec
I/DEBUG   (  289):     ip 60580f98  sp 6a76ed50  lr 6053fc00  pc 6053fbe8  cpsr 200f0010
I/DEBUG   (  289):     d0  0000000000000000  d1  0000000000000000
I/DEBUG   (  289):     d2  0000000000000000  d3  0000000000000000
I/DEBUG   (  289):     d4  02123b3200000000  d5  0000000000000000
I/DEBUG   (  289):     d6  00000000ffffffff  d7  0000000000000000
I/DEBUG   (  289):     d8  0000000000000000  d9  0000000000000000
I/DEBUG   (  289):     d10 0000000000000000  d11 0000000000000000
I/DEBUG   (  289):     d12 0000000000000000  d13 0000000000000000
I/DEBUG   (  289):     d14 0000000000000000  d15 0000000000000000
I/DEBUG   (  289):     d16 0073007200650070  d17 002e0073006e006f
I/DEBUG   (  289):     d18 6e6f697461636f6c  d19 6275745365746953
I/DEBUG   (  289):     d20 6572435f44444128  d21 636f6c6c41657461
I/DEBUG   (  289):     d22 6d654d6e6f697461  d23 74533a736f746e65
I/DEBUG   (  289):     d24 6c6c614374657320  d25 6e65202c6b636162
I/DEBUG   (  289):     d26 0301204157030151  d27 2011570301201157
I/DEBUG   (  289):     d28 5703012041570301  d29 1157030120113011
I/DEBUG   (  289):     d30 6576456863746170  d31 2020200a0a3b746e
I/DEBUG   (  289):     scr 22000017
I/DEBUG   (  289):
I/DEBUG   (  289): backtrace:
I/DEBUG   (  289):     #00  pc 00028be8  /data/app-lib/com.ChoreScore-1/libstlport_shared.so
I/DEBUG   (  289):     #01  pc 00028bfc  /data/app-lib/com.ChoreScore-1/libstlport_shared.so
I/DEBUG   (  289):
I/DEBUG   (  289): stack:
I/DEBUG   (  289):          6a76ed10  6115e9d5  /data/app-lib/com.ChoreScore-1/libChoreScore.so (invoke_delegate(void*))
I/DEBUG   (  289):          6a76ed14  65dccb38
I/DEBUG   (  289):          6a76ed18  65dccb70
I/DEBUG   (  289):          6a76ed1c  65d6100c
I/DEBUG   (  289):          6a76ed20  65dcdc40
I/DEBUG   (  289):          6a76ed24  605742b0  /data/app-lib/com.ChoreScore-1/libstlport_shared.so (_Unwind_RaiseException+24)
I/DEBUG   (  289):          6a76ed28  00000000
I/DEBUG   (  289):          6a76ed2c  00000000
I/DEBUG   (  289):          6a76ed30  65dccb70
I/DEBUG   (  289):          6a76ed34  6053fbd8  /data/app-lib/com.ChoreScore-1/libstlport_shared.so
I/DEBUG   (  289):          6a76ed38  00000000
I/DEBUG   (  289):          6a76ed3c  00000001
I/DEBUG   (  289):          6a76ed40  65dccb38
I/DEBUG   (  289):          6a76ed44  65dccb70
I/DEBUG   (  289):          6a76ed48  65d6100c
I/DEBUG   (  289):          6a76ed4c  65dccb38
I/DEBUG   (  289):     #00  6a76ed50  6058200c  /data/app-lib/com.ChoreScore-1/libstlport_shared.so
I/DEBUG   (  289):          6a76ed54  6053fc00  /data/app-lib/com.ChoreScore-1/libstlport_shared.so
I/DEBUG   (  289):     #01  6a76ed58  6058200c  /data/app-lib/com.ChoreScore-1/libstlport_shared.so
I/DEBUG   (  289):          6a76ed5c  6053fca4  /data/app-lib/com.ChoreScore-1/libstlport_shared.so
I/DEBUG   (  289):          6a76ed60  00000000
I/DEBUG   (  289):          6a76ed64  6053eb8c  /data/app-lib/com.ChoreScore-1/libstlport_shared.so
I/DEBUG   (  289):          6a76ed68  00000000
I/DEBUG   (  289):          6a76ed6c  6053db38  /data/app-lib/com.ChoreScore-1/libstlport_shared.so (__cxa_get_globals_fast)
I/DEBUG   (  289):          6a76ed70  65dccbc8
I/DEBUG   (  289):          6a76ed74  000004f2
I/DEBUG   (  289):          6a76ed78  6127bc78  /data/app-lib/com.ChoreScore-1/libChoreScore.so
I/DEBUG   (  289):          6a76ed7c  6053dc40  /data/app-lib/com.ChoreScore-1/libstlport_shared.so (__cxa_throw+56)
I/DEBUG   (  289):          6a76ed80  00000002
I/DEBUG   (  289):          6a76ed84  611708c5  /data/app-lib/com.ChoreScore-1/libChoreScore.so (uThrowable::ThrowIndexOutOfRange(char const*, int)+48)
I/DEBUG   (  289):          6a76ed88  65dcdc40
I/DEBUG   (  289):          6a76ed8c  65dcdc40
I/DEBUG   (  289):          6a76ed90  6115e9d5  /data/app-lib/com.ChoreScore-1/libChoreScore.so (invoke_delegate(void*))
I/DEBUG   (  289):          6a76ed94  61170a47  /data/app-lib/com.ChoreScore-1/libChoreScore.so (uDelegate::InvokeVoid()+86)
I/DEBUG   (  289):
I/DEBUG   (  289): memory near r0:
I/DEBUG   (  289):     6053fbb8 e5970008 e1a01006 e1a02005 e1a03004
I/DEBUG   (  289):     6053fbc8 e590c000 e59cc010 e12fff3c e8bd80f8
I/DEBUG   (  289):     6053fbd8 e92d4008 e30c3fff e34d3ead e3a02000
I/DEBUG   (  289):     6053fbe8 e543254e ebffe90a e3500000 e92d4008
I/DEBUG   (  289):     6053fbf8 0a000001 e12fff30 ebfffff4 e59f0014
I/DEBUG   (  289):     6053fc08 e08f0000 e12fff30 eafffffa ebffe90c
I/DEBUG   (  289):     6053fc18 ebffe914 ebffffed ffffffc8 e59f3028
I/DEBUG   (  289):     6053fc28 e3a02000 e08f3003 f57ff05f e1930f9f
I/DEBUG   (  289):     6053fc38 e0801002 e1830f91 e3300000 1afffffa
I/DEBUG   (  289):     6053fc48 e0410002 f57ff05f e12fff1e 000423d8
I/DEBUG   (  289):     6053fc58 e2502000 0a000008 e59f3028 e08f3003
I/DEBUG   (  289):     6053fc68 e1930f9f e1831f92 e3310000 1afffffb
I/DEBUG   (  289):     6053fc78 f57ff05f f57ff05f e12fff1e e59f2008
I/DEBUG   (  289):     6053fc88 e08f2002 eafffff3 000423a0 ffffff48
I/DEBUG   (  289):     6053fc98 e92d4008 ebffe941 ebffffd2 e92d4008
I/DEBUG   (  289):     6053fca8 ebffe8e4 e59f3028 e3a02000 e08f3003
I/DEBUG   (  289):
I/DEBUG   (  289): memory near r1:
I/DEBUG   (  289):     6053fbb8 e5970008 e1a01006 e1a02005 e1a03004
I/DEBUG   (  289):     6053fbc8 e590c000 e59cc010 e12fff3c e8bd80f8
I/DEBUG   (  289):     6053fbd8 e92d4008 e30c3fff e34d3ead e3a02000
I/DEBUG   (  289):     6053fbe8 e543254e ebffe90a e3500000 e92d4008
I/DEBUG   (  289):     6053fbf8 0a000001 e12fff30 ebfffff4 e59f0014
I/DEBUG   (  289):     6053fc08 e08f0000 e12fff30 eafffffa ebffe90c
I/DEBUG   (  289):     6053fc18 ebffe914 ebffffed ffffffc8 e59f3028
I/DEBUG   (  289):     6053fc28 e3a02000 e08f3003 f57ff05f e1930f9f
I/DEBUG   (  289):     6053fc38 e0801002 e1830f91 e3300000 1afffffa
I/DEBUG   (  289):     6053fc48 e0410002 f57ff05f e12fff1e 000423d8
I/DEBUG   (  289):     6053fc58 e2502000 0a000008 e59f3028 e08f3003
I/DEBUG   (  289):     6053fc68 e1930f9f e1831f92 e3310000 1afffffb
I/DEBUG   (  289):     6053fc78 f57ff05f f57ff05f e12fff1e e59f2008
I/DEBUG   (  289):     6053fc88 e08f2002 eafffff3 000423a0 ffffff48
I/DEBUG   (  289):     6053fc98 e92d4008 ebffe941 ebffffd2 e92d4008
I/DEBUG   (  289):     6053fca8 ebffe8e4 e59f3028 e3a02000 e08f3003
I/DEBUG   (  289):
I/DEBUG   (  289): memory near r4:
I/DEBUG   (  289):     65dccb18 00000001 65dccb28 65dccae8 00000013
I/DEBUG   (  289):     65dccb28 61299310 65dccb10 65dccb40 000000ab
I/DEBUG   (  289):     65dccb38 00000000 61299258 6116f7ed 6053fca4
I/DEBUG   (  289):     65dccb48 6053fbd8 00000000 00000001 00000000
I/DEBUG   (  289):     65dccb58 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dccb68 00000000 00000000 432b2b00 474e5543
I/DEBUG   (  289):     65dccb78 6053dc00 00000000 00000000 00000000
I/DEBUG   (  289):     65dccb88 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dccb98 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dccba8 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dccbb8 400a9388 400d9c30 00000001 00000000
I/DEBUG   (  289):     65dccbc8 61299270 65dcdf10 6127bc78 000004f2
I/DEBUG   (  289):     65dccbd8 65dcc9f8 00000013 400ea1c8 400ea1c8
I/DEBUG   (  289):     65dccbe8 00000010 0000002b 62238748 00000000
I/DEBUG   (  289):     65dccbf8 00000001 65daee08 61111195 00000000
I/DEBUG   (  289):     65dccc08 65daee08 00000000 0000000b 0000002b
I/DEBUG   (  289):
I/DEBUG   (  289): memory near r5:
I/DEBUG   (  289):     65dccb50 00000001 00000000 00000000 00000000
I/DEBUG   (  289):     65dccb60 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dccb70 432b2b00 474e5543 6053dc00 00000000
I/DEBUG   (  289):     65dccb80 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dccb90 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dccba0 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dccbb0 00000000 00000000 400a9388 400d9c30
I/DEBUG   (  289):     65dccbc0 00000001 00000000 61299270 65dcdf10
I/DEBUG   (  289):     65dccbd0 6127bc78 000004f2 65dcc9f8 00000013
I/DEBUG   (  289):     65dccbe0 400ea1c8 400ea1c8 00000010 0000002b
I/DEBUG   (  289):     65dccbf0 62238748 00000000 00000001 65daee08
I/DEBUG   (  289):     65dccc00 61111195 00000000 65daee08 00000000
I/DEBUG   (  289):     65dccc10 0000000b 0000002b 62238748 00000000
I/DEBUG   (  289):     65dccc20 00000001 65daee08 611112ad 00000000
I/DEBUG   (  289):     65dccc30 65daee08 00000000 00000065 0000002b
I/DEBUG   (  289):     65dccc40 00000001 00000010 00000000 00000000
I/DEBUG   (  289):
I/DEBUG   (  289): memory near r6:
I/DEBUG   (  289):     65d60fec 00000001 00000000 00000007 00000007
I/DEBUG   (  289):     65d60ffc 00000007 00000000 00000000 65c68470
I/DEBUG   (  289):     65d6100c 65dccb38 00000000 00000000 65d61024
I/DEBUG   (  289):     65d6101c 00000000 00000000 65d61030 00000000
I/DEBUG   (  289):     65d6102c 00000000 65d6103c 00000000 00000000
I/DEBUG   (  289):     65d6103c 65d61048 00000000 00000000 65d61054
I/DEBUG   (  289):     65d6104c 00000000 00000000 65d61060 00000000
I/DEBUG   (  289):     65d6105c 00000000 65d6106c 00000000 00000000
I/DEBUG   (  289):     65d6106c 65d61078 00000000 00000000 65d61084
I/DEBUG   (  289):     65d6107c 00000000 00000000 65d61090 00000000
I/DEBUG   (  289):     65d6108c 00000000 65d6109c 00000000 00000000
I/DEBUG   (  289):     65d6109c 65d610a8 00000000 00000000 65d610b4
I/DEBUG   (  289):     65d610ac 00000000 00000000 65d610c0 00000000
I/DEBUG   (  289):     65d610bc 00000000 65d610cc 00000000 00000000
I/DEBUG   (  289):     65d610cc 65d610d8 00000000 00000000 65d610e4
I/DEBUG   (  289):     65d610dc 00000000 00000000 65d610f0 00000000
I/DEBUG   (  289):
I/DEBUG   (  289): memory near r7:
I/DEBUG   (  289):     65dcdc20 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dcdc30 00000000 00000000 65dcdaf8 0000002b
I/DEBUG   (  289):     65dcdc40 6223ad18 00000000 00000003 65fa5348
I/DEBUG   (  289):     65dcdc50 65fa57c8 622e2150 65dcd650 65fa7990
I/DEBUG   (  289):     65dcdc60 622e4248 00000021 400ea1d8 65c68e30
I/DEBUG   (  289):     65dcdc70 00000000 00000000 ffffffff 00000000
I/DEBUG   (  289):     65dcdc80 00000020 0000024a 65dcd9f8 65cf7d30
I/DEBUG   (  289):     65dcdc90 00000000 6a671000 000fe000 00001000
I/DEBUG   (  289):     65dcdca0 00000000 00000000 00006396 00000001
I/DEBUG   (  289):     65dcdcb0 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dcdcc0 6a76edd0 65dce000 00000000 00000000
I/DEBUG   (  289):     65dcdcd0 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dcdce0 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dcdcf0 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dcdd00 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dcdd10 00000000 00000000 00000000 00000000
I/DEBUG   (  289):
I/DEBUG   (  289): memory near r8:
I/DEBUG   (  289):     6115e9b4 bf00bd10 0013fcf0 4604b510 ffeaf7ff
I/DEBUG   (  289):     6115e9c4 bd106020 4604b510 ffdaf7ff bd106020
I/DEBUG   (  289):     6115e9d4 b083b530 4605ac01 f0104620 4628f981
I/DEBUG   (  289):     6115e9e4 fc8cf010 f0124628 4620f801 fd64f010
I/DEBUG   (  289):     6115e9f4 b0032000 4620bd30 fd5ef010 ef2ef65a
I/DEBUG   (  289):     6115ea04 b5104b15 681b447b 68c04604 f7dc6819
I/DEBUG   (  289):     6115ea14 b920fcad e8bd68e0 f07b4010 2010bcfd
I/DEBUG   (  289):     6115ea24 ef28f65a f7e04604 4a0cff95 f2404601
I/DEBUG   (  289):     6115ea34 46206316 f011447a 4909fd0f 4a094620
I/DEBUG   (  289):     6115ea44 68094479 6812447a ef1af65a f65a4620
I/DEBUG   (  289):     6115ea54 f65aef1e bf00ef04 0013d4e4 0011bd6c
I/DEBUG   (  289):     6115ea64 0013bd78 0013bd78 b5104b15 681b447b
I/DEBUG   (  289):     6115ea74 68c04604 f7dc6819 b920fc79 e8bd68e0
I/DEBUG   (  289):     6115ea84 f07b4010 2010bcd1 eef4f65a f7e04604
I/DEBUG   (  289):     6115ea94 4a0cff61 f2404601 46206325 f011447a
I/DEBUG   (  289):     6115eaa4 4909fcdb 4a094620 68094479 6812447a
I/DEBUG   (  289):
I/DEBUG   (  289): memory near r9:
I/DEBUG   (  289):     6a670fe0 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     6a670ff0 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     6a671000 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     6a671010 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     6a671020 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     6a671030 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     6a671040 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     6a671050 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     6a671060 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     6a671070 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     6a671080 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     6a671090 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     6a6710a0 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     6a6710b0 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     6a6710c0 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     6a6710d0 00000000 00000000 00000000 00000000
I/DEBUG   (  289):
I/DEBUG   (  289): memory near sl:
I/DEBUG   (  289):     65dcdc58 65dcd650 65fa7990 622e4248 00000021
I/DEBUG   (  289):     65dcdc68 400ea1d8 65c68e30 00000000 00000000
I/DEBUG   (  289):     65dcdc78 ffffffff 00000000 00000020 0000024a
I/DEBUG   (  289):     65dcdc88 65dcd9f8 65cf7d30 00000000 6a671000
I/DEBUG   (  289):     65dcdc98 000fe000 00001000 00000000 00000000
I/DEBUG   (  289):     65dcdca8 00006396 00000001 00000000 00000000
I/DEBUG   (  289):     65dcdcb8 00000000 00000000 6a76edd0 65dce000
I/DEBUG   (  289):     65dcdcc8 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dcdcd8 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dcdce8 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dcdcf8 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dcdd08 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dcdd18 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dcdd28 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dcdd38 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     65dcdd48 00000000 00000000 00000000 00000000
I/DEBUG   (  289):
I/DEBUG   (  289): memory near fp:
I/DEBUG   (  289):     400e82cc 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     400e82dc 00000000 00000000 ffffffff 00000000
I/DEBUG   (  289):     400e82ec 00000000 00000001 ffffffff 0000001f
I/DEBUG   (  289):     400e82fc 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     400e830c 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     400e831c 00000000 00000000 400aec5d 400aec59
I/DEBUG   (  289):     400e832c 400af60b 400af745 00000000 40d5c428
I/DEBUG   (  289):     400e833c 00000000 00000000 00000000 4177e349
I/DEBUG   (  289):     400e834c 400af7d9 404e2249 5cd64858 00000000
I/DEBUG   (  289):     400e835c 00000000 00000000 40164471 40134de1
I/DEBUG   (  289):     400e836c 6053d844 607d3f10 6116deb9 611d951d
I/DEBUG   (  289):     400e837c 6116e589 00000000 00000000 5fd6d320
I/DEBUG   (  289):     400e838c 40321041 00000000 00000000 00000000
I/DEBUG   (  289):     400e839c 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     400e83ac 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     400e83bc 00000000 00000000 00000000 00000000
I/DEBUG   (  289):
I/DEBUG   (  289): memory near ip:
I/DEBUG   (  289):     60580f78 6053fd38 6053d904 400a9a70 400be3b0
I/DEBUG   (  289):     60580f88 400a9a90 400aee6d 6053d564 6053fcac
I/DEBUG   (  289):     60580f98 6053fc24 60574298 400a9d5d 400a9d71
I/DEBUG   (  289):     60580fa8 6053dba8 6053db38 605740c4 400a9824
I/DEBUG   (  289):     60580fb8 400aa7c8 400d66c3 6053d92c 6053d948
I/DEBUG   (  289):     60580fc8 6053df20 6053dfbc 6057310c 6053f30c
I/DEBUG   (  289):     60580fd8 6053e028 6053e108 6053df68 6053e148
I/DEBUG   (  289):     60580fe8 6053e1cc 6053e280 400ae185 6053e934
I/DEBUG   (  289):     60580ff8 6053e95c 6053e930 6053e978 6053e9a0
I/DEBUG   (  289):     60581008 6053e978 6053ea10 6053e9d8 6053e9c8
I/DEBUG   (  289):     60581018 6053e9f4 6053e990 400c1a15 40082f31
I/DEBUG   (  289):     60581028 40082e81 40082dfd 6053eaf4 6053eb1c
I/DEBUG   (  289):     60581038 6053eaec 6053eb3c 6053eb64 6053eb38
I/DEBUG   (  289):     60581048 605747a4 6057379c 60574778 6053eba0
I/DEBUG   (  289):     60581058 60573808 60574738 6053d498 6053f284
I/DEBUG   (  289):     60581068 6053f2ac 6053f284 6053f30c 6053f388
I/DEBUG   (  289):
I/DEBUG   (  289): memory near sp:
I/DEBUG   (  289):     6a76ed30 65dccb70 6053fbd8 00000000 00000001
I/DEBUG   (  289):     6a76ed40 65dccb38 65dccb70 65d6100c 65dccb38
I/DEBUG   (  289):     6a76ed50 6058200c 6053fc00 6058200c 6053fca4
I/DEBUG   (  289):     6a76ed60 00000000 6053eb8c 00000000 6053db38
I/DEBUG   (  289):     6a76ed70 65dccbc8 000004f2 6127bc78 6053dc40
I/DEBUG   (  289):     6a76ed80 00000002 611708c5 65dcdc40 65dcdc40
I/DEBUG   (  289):     6a76ed90 6115e9d5 61170a47 6a76eda4 6115e9ef
I/DEBUG   (  289):     6a76eda0 00000000 00002000 65dcdc40 6a76edd0
I/DEBUG   (  289):     6a76edb0 65dcdc88 400a92e4 65dcdc40 65dcdc88
I/DEBUG   (  289):     6a76edc0 6a76edd0 00000002 00000078 400a947c
I/DEBUG   (  289):     6a76edd0 6a76edd0 65dcdc88 00000016 00000000
I/DEBUG   (  289):     6a76ede0 00000000 3f57cffa 00000000 00000000
I/DEBUG   (  289):     6a76edf0 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     6a76ee00 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     6a76ee10 00000000 00000000 00000000 00000000
I/DEBUG   (  289):     6a76ee20 00000000 00000000 00000000 00000000
I/DEBUG   (  289):
I/DEBUG   (  289): code around pc:
I/DEBUG   (  289):     6053fbc8 e590c000 e59cc010 e12fff3c e8bd80f8
I/DEBUG   (  289):     6053fbd8 e92d4008 e30c3fff e34d3ead e3a02000
I/DEBUG   (  289):     6053fbe8 e543254e ebffe90a e3500000 e92d4008
I/DEBUG   (  289):     6053fbf8 0a000001 e12fff30 ebfffff4 e59f0014
I/DEBUG   (  289):     6053fc08 e08f0000 e12fff30 eafffffa ebffe90c
I/DEBUG   (  289):     6053fc18 ebffe914 ebffffed ffffffc8 e59f3028
I/DEBUG   (  289):     6053fc28 e3a02000 e08f3003 f57ff05f e1930f9f
I/DEBUG   (  289):     6053fc38 e0801002 e1830f91 e3300000 1afffffa
I/DEBUG   (  289):     6053fc48 e0410002 f57ff05f e12fff1e 000423d8
I/DEBUG   (  289):     6053fc58 e2502000 0a000008 e59f3028 e08f3003
I/DEBUG   (  289):     6053fc68 e1930f9f e1831f92 e3310000 1afffffb
I/DEBUG   (  289):     6053fc78 f57ff05f f57ff05f e12fff1e e59f2008
I/DEBUG   (  289):     6053fc88 e08f2002 eafffff3 000423a0 ffffff48
I/DEBUG   (  289):     6053fc98 e92d4008 ebffe941 ebffffd2 e92d4008
I/DEBUG   (  289):     6053fca8 ebffe8e4 e59f3028 e3a02000 e08f3003
I/DEBUG   (  289):     6053fcb8 f57ff05f e1930f9f e0801002 e1830f91
I/DEBUG   (  289):
I/DEBUG   (  289): code around lr:
I/DEBUG   (  289):     6053fbe0 e34d3ead e3a02000 e543254e ebffe90a
I/DEBUG   (  289):     6053fbf0 e3500000 e92d4008 0a000001 e12fff30
I/DEBUG   (  289):     6053fc00 ebfffff4 e59f0014 e08f0000 e12fff30
I/DEBUG   (  289):     6053fc10 eafffffa ebffe90c ebffe914 ebffffed
I/DEBUG   (  289):     6053fc20 ffffffc8 e59f3028 e3a02000 e08f3003
I/DEBUG   (  289):     6053fc30 f57ff05f e1930f9f e0801002 e1830f91
I/DEBUG   (  289):     6053fc40 e3300000 1afffffa e0410002 f57ff05f
I/DEBUG   (  289):     6053fc50 e12fff1e 000423d8 e2502000 0a000008
I/DEBUG   (  289):     6053fc60 e59f3028 e08f3003 e1930f9f e1831f92
I/DEBUG   (  289):     6053fc70 e3310000 1afffffb f57ff05f f57ff05f
I/DEBUG   (  289):     6053fc80 e12fff1e e59f2008 e08f2002 eafffff3
I/DEBUG   (  289):     6053fc90 000423a0 ffffff48 e92d4008 ebffe941
I/DEBUG   (  289):     6053fca0 ebffffd2 e92d4008 ebffe8e4 e59f3028
I/DEBUG   (  289):     6053fcb0 e3a02000 e08f3003 f57ff05f e1930f9f
I/DEBUG   (  289):     6053fcc0 e0801002 e1830f91 e3300000 1afffffa
I/DEBUG   (  289):     6053fcd0 e0410002 f57ff05f e12fff1e 0004234c
I/DEBUG   (  289):
I/DEBUG   (  289): memory map around fault addr deadcab1:
I/DEBUG   (  289):     bec57000-bec78000 rw- [stack]
I/DEBUG   (  289):     (no map for address)
I/DEBUG   (  289):     ffff0000-ffff1000 r-x [vectors]
I/Adreno-EGL( 1485): <qeglDrvAPI_eglInitialize:385>: EGL 1.4 QUALCOMM build:  ()
I/Adreno-EGL( 1485): OpenGL ES Shader Compiler Version: E031.24.00.02
I/Adreno-EGL( 1485): Build Date: 01/20/14 Mon
I/Adreno-EGL( 1485): Local Branch: PMH2-KK_3.5-RB1-AU61-554722-586267-set2
I/Adreno-EGL( 1485): Remote Branch:
I/Adreno-EGL( 1485): Local Patches:
I/Adreno-EGL( 1485): Reconstruct Branch:
```

**Comment by knatten** [comment]
Fixed
